sudo: false
language: node_js
cache:
  directories:
  - bower_components
  - node_modules
env:
  global:
  - GH_REF=github.com/amercier/todomvc-speedtest-angular.git
  - secure: "NTN4IOY1FzqvHhTsfjBMqaDMl5Xw4eh3mwpXC0Ty7expByJKJPD0TmHqAKSYIz8DDhtdguMRgzI1KA8xDSi8D/ZeW5QOiSUcrVJfD0sRo2gL50fkXJlMbe8BXaskYLv1SQ3btlrnAdM6xWoVJeu0z2sFXGjqFXLDn1SntMxNth4="
after_success:
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && ./build.sh dist /todomvc-speedtest-angular || echo "Pull request. Skipping build" >&2
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && ./deploy.sh dist || echo "Pull request. Skipping deployment" >&2
